dist: xenial

matrix:
  include:
    - language: bash
      install:
        - set -e
        - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.6/terraform_0.12.6_linux_amd64.zip
        - unzip /tmp/terraform -d /tmp
        - chmod +x /tmp/terraform
        - /tmp/terraform -version
      script:
        - .ci/validate-terraform.sh
    - language: node_js
      install:
        - npm install -g jsonlint
      script:
        - jsonlint salt/monitoring/provisioning/dashboards/*.json

notifications:
  email: true
