dist: xenial

language: bash

notifications:
  email: true

before_script:
  - set -e
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.6/terraform_0.12.6_linux_amd64.zip
  - unzip /tmp/terraform -d /tmp
  - chmod +x /tmp/terraform
  - /tmp/terraform -version

script:
  - .ci/validate-terraform.sh
