# Sample config for Prometheus.
global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s

{% if grains.get('monitored_services') %}
scrape_configs:
  - job_name: hanadb
    static_configs:
      - targets:
        {% for ip in grains['monitored_services'] %}
        - "{{ ip }}:8001" # 8801: hanadb exporter port
        {% endfor %}

  - job_name: node
    static_configs:
      - targets:
        {% for ip in grains['monitored_services'] %}
        - "{{ ip }}:9100" # 9100: node exporter port
        {% endfor %}


  - job_name: cluster
    metrics_path: /metrics
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
        {% for ip in grains['monitored_services'] %}
        - "{{ ip }}:9001" # 9001: hawk-apiserver exporter port
        {% endfor %}
{% endif %}
