# Sample config for Prometheus.
global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

rule_files:
    - /etc/prometheus/rules.yml

scrape_configs:
  # in a multi-cluster scenario, add another job name called
  #  hacluster-02
  - job_name: hana-cluster
    static_configs:
      - targets:
        {% for ip in grains['monitored_hosts'] %}
        - "{{ ip }}:8001" # 8001: hanadb exporter port
        {% endfor %}
        {% for ip in grains['monitored_hosts'] %}
        - "{{ ip }}:9100" # 9100: node exporter port
        {% endfor %}
        {% for ip in grains['monitored_hosts'] %}
        - "{{ ip }}:9002" # 9002: ha_cluster_exporter metrics
        {% endfor %}

  {% if grains['drbd_monitored_hosts']|length > 0 %}
  - job_name: drbd-cluster
    static_configs:
      - targets:
        {% for ip in grains['drbd_monitored_hosts'] %}
        - "{{ ip }}:9100" # 9100: node exporter port
        {% endfor %}
        {% for ip in grains['drbd_monitored_hosts'] %}
        - "{{ ip }}:9002" # 9002: ha_cluster_exporter metrics
        {% endfor %}
  {% endif %}
