# Sample config for Prometheus.
global:
  scrape_interval: 10s # By default, scrape targets every 15 seconds.
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'hanadb'
    scrape_interval: 5s
    static_configs:
      # servive is an entry like : HOST_IP:PORT 192.XX.XX.1:8001
      {% if grains.get['monitored_services'] %}
      {% for service in grains['monitored_services'] %}
      - targets: ['{{ service }}'] # service to be monitored
      {% endfor %}
      {% endif %}
