# github-actions workflow
# this test will just run terraform without salt
name: e2e tests

on: [pull_request]

jobs:
  terraform-sap-deployment:
    runs-on: self-hosted 

    steps:
    - uses: actions/checkout@v2

       
    - name: terraform apply
      env:
        VAULT_ADDR:  "http://10.162.32.32:8200"
      run:  /tmp/terraform-apply.sh

    - name: terraform destroy
      env:
        VAULT_ADDR:  "http://10.162.32.32:8200"
      if: ${{ always() }}
      run:  /tmp/terraform-destroy.sh
